### ISSUE TITLE
Please make the whole app build in one go.

### ISSUE THREAD

**Issue by cdluv** [open-house/oh-pipeline-service#6]
Good to see some tooling which is separated from the mainstream tools.

Quite happy to be a committer on this project.... 

Having trouble building with Maven...  

./build <buildnumber> doesn't deploy to /opt unless you're root... Not keen on building apps as ROOT :-(

**Comment by pete911** [comment]
Hi,

you need oh-pipeline-domain:
git clone https://github.com/open-house/oh-pipeline-domain.git
cd oh-pipeline-domain/
./build 7

cd ..
git clone https://github.com/open-house/oh-pipeline-service.git
mvn clean install
mvn jetty:run

build script is meant to run in automated environment (for example on Jenkins, so your shell command would be './build $BUILD_NUMBER'), the number is build number. As these projects are not in maven central yet, you have to install domain locally. If you don't want to run bulid script, just change version in pom and run maven clean install.

You need db set up as well for service.

build script doesn't deploy anything to /opt and you don't have to be root. It runs maven plus creates deb package. This script will be separate project in the future so it is easy to create different packages. You can use mvn jetty:run to run your application without installing it.

This is still early stage and I'd be happy if you could contribute. Let me know if everything is clear and I can send you brief description of the project, where it's going etc.

thanks

**Comment by cdluv** [comment]
Thanks for the response.
I understand they are not in Maven Central yet. Can't you put the domain and the oh-pipeline-service in a multi-module project and build them at the same time?

P.S You can use the Maven Versions plugin to update the POM versions rather than using SED...

Thanks

**Comment by pete911** [comment]
I will have a look at Maven Versions (thanks for that).

Domain is separate project, service and client depend on that. So I don't want to be incrementing build number of the domain (and creating new artifact) when I change the service.

Some people don't want to build service, they just want to work on UI, so they would need pipeline-domain and pipeline-client. This way it's not coupled.

I'd like to have automated uploads to maven central in the future, so you won't have these problems.

Let me know if I'm missing something, I'm opened to ideas.

**Comment by pete911** [comment]
to sum it up, the whole project looks like this (arrows indicate dependencies):
service -> domain <- client <- ui
it is supposed to be flexible, so you can have just service without ui and so on.

I have triggers for every project, so they can be built quickly and independently on jenkins. (I'm not sure if I can have triggers for subdirectories on github - this would be required for multimodule as it would be in one repo)

Service and UI are packaged (.deb) and uploaded to deb repo. Domain and client will be in the future automatically uploaded to maven central.
